# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI DEV

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      DATABASE_HOST: 127.0.0.1
      DATABASE_USER: root
      DATABASE_PASS: root
      DATABASE_SCHEMA_TEST: db_caixapet_test
      DATABASE_PORT: 3306

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present

    - name: Set up MySQL
      run: sudo /etc/init.d/mysql start mysql -e 'CREATE DATABASE ${{ env.DATABASE_SCHEMA_TEST }};' -u${{ env.DATABASE_USER }} -p${{ env.DATABASE_PASS }}

    - name: Create tables in MySQL
      run: sudo mysql -h ${{ env.DATABASE_HOST }} -u${{ env.DATABASE_USER }} -p${{ env.DATABASE_PASS }} < ${{ github.workspace }}/sql/db_petcaixa_test.sql

    - run: npm test
